/* eslint-disable @typescript-eslint/naming-convention */
import * as fs from 'fs';
import { v4 as uuidv4 } from 'uuid';

import {
  getUserLoraDetails,
  uploadFileToFirebase,
} from '@/utils/ReplyHelper/FirebaseHelpers';

const runpodURL = process.env.RUNPOD_URL as string;
const runpodBearerToken = process.env.RUNPOD_BEARER_TOKEN as string;
const runpodApiKey = process.env.RUNPOD_API_KEY as string;

export async function saveImageToDisk(base64Content: string, filename: string) {
  try {
    const fileContent = Buffer.from(base64Content, 'base64');
    const filePath = `${filename}.ignore.png`;
    fs.writeFileSync(filePath, fileContent);
  } catch (error) {
    console.error('Error saving image to disk:', error);
    throw new Error('Failed to save image to disk');
  }
}

export async function createTrainingJob(
  image_urls: string[],
  model_name: string,
) {
  try {
    const response = await fetch(
      'https://api.runpod.ai/v2/rob1itdpqaacn3/run',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${runpodBearerToken}`,
        },
        body: JSON.stringify({
          input: {
            api_key: runpodApiKey,
            image_urls,
            model_name,
          },
        }),
      },
    );

    if (!response.ok) {
      throw new Error(`RunPod request failed with status: ${response.status}`);
    }

    const jobResponse = await response.json();
    return jobResponse.id;
  } catch (error) {
    console.error('Error creating training job:', error);
    throw new Error('Failed to create training job');
  }
}
/**
 * 
 * @param jobId 
 *
 * @returns {Promise<TrainingJobStatus>}
interface TrainingJobOutput {
  firebase_path: string;
  firebase_url: string;
  status: string;
}

interface TrainingJobStatus {
  delayTime: number;
  executionTime: number;
  id: string;
  output: TrainingJobOutput;
  status: string;
}
 */
export async function checkTrainingJob(jobId: string) {
  try {
    const response = await fetch(
      `https://api.runpod.ai/v2/rob1itdpqaacn3/status/${jobId}`,
      {
        method: 'GET',
        headers: {
          Authorization: `Bearer ${runpodBearerToken}`,
        },
      },
    );

    if (!response.ok) {
      throw new Error(`RunPod request failed with status: ${response.status}`);
    }

    const jobStatus = await response.json();
    return jobStatus;
  } catch (error) {
    console.error('Error checking training job status:', error);
    throw new Error('Failed to check training job status');
  }
}

export async function generateImagesUploadToFirebaseGetURL(
  improvedPromptFromGroq: string,
  clientid: string,
): Promise<string[]> {
  try {
    const clientLoraInfo = await getUserLoraDetails(clientid);
    const lora_url = clientLoraInfo.loraURL;
    const lora_filename = clientLoraInfo.loraFilename;

    console.log('[+] got file name: ', lora_filename);

    // const improvedPromptFromGroq = await getImprovedPromptFromGroq(prompt);
    // console.log('[+] got improved prompt: ', improvedPromptFromGroq);

    const response = await fetch(runpodURL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${runpodBearerToken}`,
      },
      body: JSON.stringify({
        input: {
          num_images: 1,
          api_key: runpodApiKey,
          prompt: improvedPromptFromGroq,
          lora_url,
          lora_filename,
        },
      }),
    });

    console.log('[+] runpod res: ', JSON.stringify(response, null, 2));

    if (!response.ok) {
      throw new Error(`Runpod request failed with status: ${response.status}`);
    }

    const jobResponse = await response.json();

    const images = jobResponse?.output?.images || [];
    console.log(`got ${images.length} runpod images`);

    if (images.length === 0) {
      console.warn('No images were generated by Runpod.');
      return [];
    }

    const processPromises = images.map(async (image: string, index: number) => {
      const base64Content = image.split(';base64,').pop() || '';

      try {
        const filename = `${clientid || 'test'}_${uuidv4()}_${index + 1}.png`;
        const firebaseUrl = await uploadFileToFirebase(
          base64Content,
          clientid,
          filename,
        );
        return firebaseUrl;
      } catch (error) {
        console.error('Error processing image:', error);
        return null;
      }
    });

    const results = await Promise.all(processPromises);
    const firebaseURLs = results.filter((url): url is string => url !== null);

    return firebaseURLs;
  } catch (error) {
    console.error('Error generating images and uploading to Firebase:', error);
    throw new Error('Failed to generate and upload images');
  }
}
