import * as fs from 'fs';
import { v4 as uuidv4 } from 'uuid';

import {
  getUserLoraDetails,
  uploadFileToFirebase,
} from '@/utils/ReplyHelper/FirebaseHelpers';

const runpodURL = process.env.RUNPOD_URL as string;
const runpodBearerToken = process.env.RUNPOD_BEARER_TOKEN as string;
const runpodApiKey = process.env.RUNPOD_API_KEY as string;

export async function saveImageToDisk(base64Content: string, filename: string) {
  const fileContent = Buffer.from(base64Content, 'base64');
  // save to temp file
  const filePath = `${filename}.ignore.png`;
  // save to disk
  fs.writeFileSync(filePath, fileContent);
}

export async function generateImagesUploadToFirebaseGetURL(
  prompt: string,
  clientid: string,
): Promise<string[]> {
  const clientLoraInfo = await getUserLoraDetails(clientid);

  const response = await fetch(runpodURL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${runpodBearerToken}`,
    },
    body: JSON.stringify({
      input: {
        num_images: 1,
        api_key: runpodApiKey,
        prompt,
        lora_url: clientLoraInfo.loraURL,
        lora_filename: clientLoraInfo.loraFilename,
      },
    }),
  });

  const jobResponse = await response.json();

  const images = jobResponse?.output?.images || [];
  console.log(`got ${images.length} runpod images`);

  if (images.length === 0) {
    console.warn('No images were generated by Runpod.');
    return [];
  }

  const processPromises = images.map(async (image: string, index: number) => {
    const base64Content = image.split(';base64,').pop() || '';

    try {
      const filename = `${clientid || 'test'}_${uuidv4()}_${index + 1}.png`;

      // Upload to Firebase Storage
      const firebaseUrl = await uploadFileToFirebase(base64Content, filename);

      return firebaseUrl;
    } catch (error) {
      console.error('Error processing image:', error);
      return null;
    }
  });

  const results = await Promise.all(processPromises);
  const firebaseURLs = results.filter((url): url is string => url !== null);

  return firebaseURLs;
}
