/* eslint-disable @typescript-eslint/naming-convention */
export type PaymentIntentCreatedEvent = typeof payment_intent_created;
export type CheckoutSessionCompletedEvent = typeof checkout_session_completed;
export type PaymentIntentSucceededEvent = typeof payment_intent_succeeded;
export type ChargeSucceededEvent = typeof charge_succeeded;
export type ChargeUpdatedEvent = typeof charge_updated;

const payment_intent_succeeded = {
  id: 'evt_3Ps2gkDWnX2YhQws0rN6mmEv',
  object: 'event',
  api_version: '2024-06-20',
  created: 1724677831,
  data: {
    object: {
      id: 'pi_3Ps2gkDWnX2YhQws0obVnTjZ',
      object: 'payment_intent',
      amount: 500,
      amount_capturable: 0,
      amount_details: {
        tip: {},
      },
      amount_received: 500,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: 'automatic_async',
      client_secret:
        'pi_3Ps2gkDWnX2YhQws0obVnTjZ_secret_EfV9r4U0RMJwuDYzupKBVXx5b',
      confirmation_method: 'automatic',
      created: 1724677830,
      currency: 'usd',
      customer: null,
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: 'ch_3Ps2gkDWnX2YhQws0mXTSRHo',
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: 'pm_1Ps2giDWnX2YhQwsVdqarY6K',
      payment_method_configuration_details: null,
      payment_method_options: {
        card: {
          installments: null,
          mandate_options: null,
          network: null,
          request_three_d_secure: 'automatic',
        },
      },
      payment_method_types: ['card'],
      processing: null,
      receipt_email: null,
      review: null,
      setup_future_usage: null,
      shipping: null,
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: 'req_MfdLLtDtxGGuY6',
    idempotency_key: 'e4ed425c-86fd-4b5e-a11b-cdcd16e0c5f7',
  },
  type: 'payment_intent.succeeded',
};

const charge_succeeded = {
  id: 'evt_3Ps2gkDWnX2YhQws0FPgaF3I',
  object: 'event',
  api_version: '2024-06-20',
  created: 1724677831,
  data: {
    object: {
      id: 'ch_3Ps2gkDWnX2YhQws0mXTSRHo',
      object: 'charge',
      amount: 500,
      amount_captured: 500,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: null,
      billing_details: {
        address: {
          city: null,
          country: 'IN',
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: 'business@savibm.com',
        name: 'fsdvd fdsfsef',
        phone: null,
      },
      calculated_statement_descriptor: 'SAVI BM',
      captured: true,
      created: 1724677831,
      currency: 'usd',
      customer: null,
      description: null,
      destination: null,
      dispute: null,
      disputed: false,
      failure_balance_transaction: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: {
        network_status: 'approved_by_network',
        reason: null,
        risk_level: 'normal',
        risk_score: 28,
        seller_message: 'Payment complete.',
        type: 'authorized',
      },
      paid: true,
      payment_intent: 'pi_3Ps2gkDWnX2YhQws0obVnTjZ',
      payment_method: 'pm_1Ps2giDWnX2YhQwsVdqarY6K',
      payment_method_details: {
        card: {
          amount_authorized: 500,
          authorization_code: null,
          brand: 'visa',
          checks: {
            address_line1_check: null,
            address_postal_code_check: null,
            cvc_check: 'pass',
          },
          country: 'US',
          exp_month: 3,
          exp_year: 2025,
          extended_authorization: {
            status: 'disabled',
          },
          fingerprint: 'GMEahrtUyTn0YDqd',
          funding: 'credit',
          incremental_authorization: {
            status: 'unavailable',
          },
          installments: null,
          last4: '4242',
          mandate: null,
          multicapture: {
            status: 'unavailable',
          },
          network: 'visa',
          network_token: {
            used: false,
          },
          overcapture: {
            maximum_amount_capturable: 500,
            status: 'unavailable',
          },
          three_d_secure: null,
          wallet: null,
        },
        type: 'card',
      },
      receipt_email: null,
      receipt_number: null,
      receipt_url:
        'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xUHJjMmdEV25YMlloUXdzKMf9sbYGMgbqjWOh0Rg6LBaCoVnluV_sOOPT-p1q0bJ8rWsC7IxkombcZQ4YXq9FfJ-k3-Q-QmZ5Ghn4',
      refunded: false,
      review: null,
      shipping: null,
      source: null,
      source_transfer: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: 'req_MfdLLtDtxGGuY6',
    idempotency_key: 'e4ed425c-86fd-4b5e-a11b-cdcd16e0c5f7',
  },
  type: 'charge.succeeded',
};

const checkout_session_completed = {
  id: 'evt_1Ps2glDWnX2YhQwszlEbGE9e',
  object: 'event',
  api_version: '2024-06-20',
  created: 1724677831,
  data: {
    object: {
      id: 'cs_test_a1O4VG9kQIvhZo01Rrt5PkbZTHqwZUh7vKVenfM5RsmNBfZZVV89XcJ4LR',
      object: 'checkout.session',
      after_expiration: null,
      allow_promotion_codes: false,
      amount_subtotal: 500,
      amount_total: 500,
      automatic_tax: {
        enabled: false,
        liability: null,
        status: null,
      },
      billing_address_collection: 'auto',
      cancel_url: 'https://stripe.com',
      client_reference_id: null,
      client_secret: null,
      consent: null,
      consent_collection: null,
      created: 1724677628,
      currency: 'usd',
      currency_conversion: null,
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer: null,
      customer_creation: 'if_required',
      customer_details: {
        address: {
          city: null,
          country: 'IN',
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: 'business@savibm.com',
        name: 'fsdvd fdsfsef',
        phone: null,
        tax_exempt: 'none',
        tax_ids: [],
      },
      customer_email: null,
      expires_at: 1724764028,
      invoice: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      livemode: false,
      locale: 'auto',
      metadata: {
        clientid: '918754535859',
      },
      mode: 'payment',
      payment_intent: 'pi_3Ps2gkDWnX2YhQws0obVnTjZ',
      payment_link: 'plink_1Ps2X9DWnX2YhQws4FJcglKp',
      payment_method_collection: 'if_required',
      payment_method_configuration_details: null,
      payment_method_options: {
        card: {
          request_three_d_secure: 'automatic',
        },
      },
      payment_method_types: ['card'],
      payment_status: 'paid',
      phone_number_collection: {
        enabled: false,
      },
      recovered_from: null,
      saved_payment_method_options: null,
      setup_intent: null,
      shipping_address_collection: null,
      shipping_cost: null,
      shipping_details: null,
      shipping_options: [],
      status: 'complete',
      submit_type: 'auto',
      subscription: null,
      success_url: 'https://stripe.com',
      total_details: {
        amount_discount: 0,
        amount_shipping: 0,
        amount_tax: 0,
      },
      ui_mode: 'hosted',
      url: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: null,
    idempotency_key: null,
  },
  type: 'checkout.session.completed',
};

const payment_intent_created = {
  id: 'evt_3Ps2gkDWnX2YhQws0gEPYIJe',
  object: 'event',
  api_version: '2024-06-20',
  created: 1724677830,
  data: {
    object: {
      id: 'pi_3Ps2gkDWnX2YhQws0obVnTjZ',
      object: 'payment_intent',
      amount: 500,
      amount_capturable: 0,
      amount_details: {
        tip: {},
      },
      amount_received: 0,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: 'automatic_async',
      client_secret:
        'pi_3Ps2gkDWnX2YhQws0obVnTjZ_secret_EfV9r4U0RMJwuDYzupKBVXx5b',
      confirmation_method: 'automatic',
      created: 1724677830,
      currency: 'usd',
      customer: null,
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: null,
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: null,
      payment_method_configuration_details: null,
      payment_method_options: {
        card: {
          installments: null,
          mandate_options: null,
          network: null,
          request_three_d_secure: 'automatic',
        },
      },
      payment_method_types: ['card'],
      processing: null,
      receipt_email: null,
      review: null,
      setup_future_usage: null,
      shipping: null,
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'requires_payment_method',
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: 'req_MfdLLtDtxGGuY6',
    idempotency_key: 'e4ed425c-86fd-4b5e-a11b-cdcd16e0c5f7',
  },
  type: 'payment_intent.created',
};

const charge_updated = {
  id: 'evt_3Ps2gkDWnX2YhQws09qdFJwH',
  object: 'event',
  api_version: '2024-06-20',
  created: 1724677834,
  data: {
    object: {
      id: 'ch_3Ps2gkDWnX2YhQws0mXTSRHo',
      object: 'charge',
      amount: 500,
      amount_captured: 500,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: 'txn_3Ps2gkDWnX2YhQws0RpAfzgb',
      billing_details: {
        address: {
          city: null,
          country: 'IN',
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: 'business@savibm.com',
        name: 'fsdvd fdsfsef',
        phone: null,
      },
      calculated_statement_descriptor: 'SAVI BM',
      captured: true,
      created: 1724677831,
      currency: 'usd',
      customer: null,
      description: null,
      destination: null,
      dispute: null,
      disputed: false,
      failure_balance_transaction: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: {
        network_status: 'approved_by_network',
        reason: null,
        risk_level: 'normal',
        risk_score: 28,
        seller_message: 'Payment complete.',
        type: 'authorized',
      },
      paid: true,
      payment_intent: 'pi_3Ps2gkDWnX2YhQws0obVnTjZ',
      payment_method: 'pm_1Ps2giDWnX2YhQwsVdqarY6K',
      payment_method_details: {
        card: {
          amount_authorized: 500,
          authorization_code: null,
          brand: 'visa',
          checks: {
            address_line1_check: null,
            address_postal_code_check: null,
            cvc_check: 'pass',
          },
          country: 'US',
          exp_month: 3,
          exp_year: 2025,
          extended_authorization: {
            status: 'disabled',
          },
          fingerprint: 'GMEahrtUyTn0YDqd',
          funding: 'credit',
          incremental_authorization: {
            status: 'unavailable',
          },
          installments: null,
          last4: '4242',
          mandate: null,
          multicapture: {
            status: 'unavailable',
          },
          network: 'visa',
          network_token: {
            used: false,
          },
          overcapture: {
            maximum_amount_capturable: 500,
            status: 'unavailable',
          },
          three_d_secure: null,
          wallet: null,
        },
        type: 'card',
      },
      receipt_email: null,
      receipt_number: null,
      receipt_url:
        'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xUHJjMmdEV25YMlloUXdzKMr9sbYGMgZQa0JpTCs6LBa7wj5sfSpCupiHoGe142k_VHskOH_lm4d_4PG4TDkseW-5E2PbHLXjuMT3',
      refunded: false,
      review: null,
      shipping: null,
      source: null,
      source_transfer: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
    previous_attributes: {
      balance_transaction: null,
      receipt_url:
        'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xUHJjMmdEV25YMlloUXdzKMr9sbYGMgb5vWB9lDo6LBYovD-RCeE6aDXZurR0mesQmF8rp3eEsakCd2HhTR_7oXpEVj8UzzI5qKRu',
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: null,
    idempotency_key: null,
  },
  type: 'charge.updated',
};
