/* eslint-disable @typescript-eslint/naming-convention */
export type PaymentIntentCreatedEvent = typeof payment_intent_created;
export type InvoicePaymentSucceededEvent = typeof invoice_payment_succeeded;
export type CustomerSubscriptionUpdatedEvent =
  typeof customer_subscription_updated;
export type CheckoutSessionCompletedEvent = typeof checkout_session_completed;
export type PaymentIntentSucceededEvent = typeof payment_intent_succeeded;
export type ChargeSucceededEvent = typeof charge_succeeded;
export type ChargeUpdatedEvent = typeof charge_updated;

const payment_intent_succeeded = {
  id: 'evt_3Ps2gkDWnX2YhQws0rN6mmEv',
  object: 'event',
  api_version: '2024-06-20',
  created: 1724677831,
  data: {
    object: {
      id: 'pi_3Ps2gkDWnX2YhQws0obVnTjZ',
      object: 'payment_intent',
      amount: 500,
      amount_capturable: 0,
      amount_details: {
        tip: {},
      },
      amount_received: 500,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: 'automatic_async',
      client_secret:
        'pi_3Ps2gkDWnX2YhQws0obVnTjZ_secret_EfV9r4U0RMJwuDYzupKBVXx5b',
      confirmation_method: 'automatic',
      created: 1724677830,
      currency: 'usd',
      customer: null,
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: 'ch_3Ps2gkDWnX2YhQws0mXTSRHo',
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: 'pm_1Ps2giDWnX2YhQwsVdqarY6K',
      payment_method_configuration_details: null,
      payment_method_options: {
        card: {
          installments: null,
          mandate_options: null,
          network: null,
          request_three_d_secure: 'automatic',
        },
      },
      payment_method_types: ['card'],
      processing: null,
      receipt_email: null,
      review: null,
      setup_future_usage: null,
      shipping: null,
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: 'req_MfdLLtDtxGGuY6',
    idempotency_key: 'e4ed425c-86fd-4b5e-a11b-cdcd16e0c5f7',
  },
  type: 'payment_intent.succeeded',
};

const invoice_payment_succeeded = {
  object: {
    id: 'in_1PvJqHDWnX2YhQwscdNfC5qz',
    object: 'invoice',
    account_country: 'AE',
    account_name: 'Savi Business Management LLC',
    account_tax_ids: null,
    amount_due: 999,
    amount_paid: 999,
    amount_remaining: 0,
    amount_shipping: 0,
    application: null,
    application_fee_amount: null,
    attempt_count: 1,
    attempted: true,
    auto_advance: false,
    automatic_tax: {
      enabled: false,
      liability: null,
      status: null,
    },
    automatically_finalizes_at: null,
    billing_reason: 'subscription_create',
    charge: 'ch_3PvJqIDWnX2YhQws3f860KFA',
    collection_method: 'charge_automatically',
    created: 1725458753,
    currency: 'usd',
    custom_fields: null,
    customer: 'cus_Qmtdxn1M9MwIAu',
    customer_address: {
      city: null,
      country: 'IN',
      line1: null,
      line2: null,
      postal_code: null,
      state: null,
    },
    customer_email: 'gsi@fk.cl',
    customer_name: 'test',
    customer_phone: null,
    customer_shipping: null,
    customer_tax_exempt: 'none',
    customer_tax_ids: [],
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: {
      id: 'di_1PvJqHDWnX2YhQwsoK75Zis3',
      object: 'discount',
      checkout_session: null,
      coupon: {
        id: 'BypKDb3P',
        object: 'coupon',
        amount_off: 1000,
        created: 1725299965,
        currency: 'usd',
        duration: 'once',
        duration_in_months: null,
        livemode: false,
        max_redemptions: null,
        metadata: {},
        name: 'MARI Referral',
        percent_off: null,
        redeem_by: null,
        times_redeemed: 2,
        valid: true,
      },
      customer: 'cus_Qmtdxn1M9MwIAu',
      end: null,
      invoice: null,
      invoice_item: null,
      promotion_code: 'promo_1PueXCDWnX2YhQwseJKW5Q7y',
      start: 1725458753,
      subscription: 'sub_1PvJqHDWnX2YhQwsHGDnxFSC',
      subscription_item: null,
    },
    discounts: ['di_1PvJqHDWnX2YhQwsoK75Zis3'],
    due_date: null,
    effective_at: 1725458753,
    ending_balance: 0,
    footer: null,
    from_invoice: null,
    hosted_invoice_url:
      'https://invoice.stripe.com/i/acct_1Prc2gDWnX2YhQws/test_YWNjdF8xUHJjMmdEV25YMlloUXdzLF9RbXRkTDBDTVpoWHlPbDNxUVd4MmFpS2lHb0hrbkRTLDExNTk5OTU1Ng0200fuIH4c3I?s=ap',
    invoice_pdf:
      'https://pay.stripe.com/invoice/acct_1Prc2gDWnX2YhQws/test_YWNjdF8xUHJjMmdEV25YMlloUXdzLF9RbXRkTDBDTVpoWHlPbDNxUVd4MmFpS2lHb0hrbkRTLDExNTk5OTU1Ng0200fuIH4c3I/pdf?s=ap',
    issuer: {
      type: 'self',
    },
    last_finalization_error: null,
    latest_revision: null,
    lines: {
      object: 'list',
      data: [
        {
          id: 'il_1PvJqHDWnX2YhQwsVioLsxYA',
          object: 'line_item',
          amount: 1999,
          amount_excluding_tax: 1999,
          currency: 'usd',
          description: '1 × Unlimited Creativity - 1 Month (at $19.99 / month)',
          discount_amounts: [
            {
              amount: 1000,
              discount: 'di_1PvJqHDWnX2YhQwsoK75Zis3',
            },
          ],
          discountable: true,
          discounts: [],
          invoice: 'in_1PvJqHDWnX2YhQwscdNfC5qz',
          livemode: false,
          metadata: {},
          period: {
            end: 1728050753,
            start: 1725458753,
          },
          plan: {
            id: 'price_1PueW9DWnX2YhQws6s7otplP',
            object: 'plan',
            active: true,
            aggregate_usage: null,
            amount: 1999,
            amount_decimal: '1999',
            billing_scheme: 'per_unit',
            created: 1725299901,
            currency: 'usd',
            interval: 'month',
            interval_count: 1,
            livemode: false,
            metadata: {},
            meter: null,
            nickname: null,
            product: 'prod_QmCwB1erhuDH5n',
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: 'licensed',
          },
          price: {
            id: 'price_1PueW9DWnX2YhQws6s7otplP',
            object: 'price',
            active: true,
            billing_scheme: 'per_unit',
            created: 1725299901,
            currency: 'usd',
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: 'prod_QmCwB1erhuDH5n',
            recurring: {
              aggregate_usage: null,
              interval: 'month',
              interval_count: 1,
              meter: null,
              trial_period_days: null,
              usage_type: 'licensed',
            },
            tax_behavior: 'unspecified',
            tiers_mode: null,
            transform_quantity: null,
            type: 'recurring',
            unit_amount: 1999,
            unit_amount_decimal: '1999',
          },
          proration: false,
          proration_details: {
            credited_items: null,
          },
          quantity: 1,
          subscription: 'sub_1PvJqHDWnX2YhQwsHGDnxFSC',
          subscription_item: 'si_QmtdaLW7hlHu9Z',
          tax_amounts: [],
          tax_rates: [],
          type: 'subscription',
          unit_amount_excluding_tax: '1999',
        },
      ],
      has_more: false,
      total_count: 1,
      url: '/v1/invoices/in_1PvJqHDWnX2YhQwscdNfC5qz/lines',
    },
    livemode: false,
    metadata: {},
    next_payment_attempt: null,
    number: '78A41B7A-0001',
    on_behalf_of: null,
    paid: true,
    paid_out_of_band: false,
    payment_intent: 'pi_3PvJqIDWnX2YhQws3hhmKxox',
    payment_settings: {
      default_mandate: null,
      payment_method_options: {
        acss_debit: null,
        bancontact: null,
        card: {
          request_three_d_secure: 'automatic',
        },
        customer_balance: null,
        konbini: null,
        sepa_debit: null,
        us_bank_account: null,
      },
      payment_method_types: null,
    },
    period_end: 1725458753,
    period_start: 1725458753,
    post_payment_credit_notes_amount: 0,
    pre_payment_credit_notes_amount: 0,
    quote: null,
    receipt_number: null,
    rendering: null,
    shipping_cost: null,
    shipping_details: null,
    starting_balance: 0,
    statement_descriptor: null,
    status: 'paid',
    status_transitions: {
      finalized_at: 1725458753,
      marked_uncollectible_at: null,
      paid_at: 1725458755,
      voided_at: null,
    },
    subscription: 'sub_1PvJqHDWnX2YhQwsHGDnxFSC',
    subscription_details: {
      metadata: {},
    },
    subtotal: 1999,
    subtotal_excluding_tax: 1999,
    tax: null,
    test_clock: null,
    total: 999,
    total_discount_amounts: [
      {
        amount: 1000,
        discount: 'di_1PvJqHDWnX2YhQwsoK75Zis3',
      },
    ],
    total_excluding_tax: 999,
    total_tax_amounts: [],
    transfer_data: null,
    webhooks_delivered_at: 1725458753,
  },
  previous_attributes: null,
};

const customer_subscription_updated = {
  object: {
    id: 'sub_1PvJqHDWnX2YhQwsHGDnxFSC',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: {
      enabled: false,
      liability: null,
    },
    billing_cycle_anchor: 1725458753,
    billing_cycle_anchor_config: null,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: {
      comment: null,
      feedback: null,
      reason: null,
    },
    collection_method: 'charge_automatically',
    created: 1725458753,
    currency: 'usd',
    current_period_end: 1728050753,
    current_period_start: 1725458753,
    customer: 'cus_Qmtdxn1M9MwIAu',
    days_until_due: null,
    default_payment_method: 'pm_1PvJqGDWnX2YhQws9bHQyJrX',
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    discounts: [],
    ended_at: null,
    invoice_settings: {
      account_tax_ids: null,
      issuer: {
        type: 'self',
      },
    },
    items: {
      object: 'list',
      data: [
        {
          id: 'si_QmtdaLW7hlHu9Z',
          object: 'subscription_item',
          billing_thresholds: null,
          created: 1725458754,
          discounts: [],
          metadata: {},
          plan: {
            id: 'price_1PueW9DWnX2YhQws6s7otplP',
            object: 'plan',
            active: true,
            aggregate_usage: null,
            amount: 1999,
            amount_decimal: '1999',
            billing_scheme: 'per_unit',
            created: 1725299901,
            currency: 'usd',
            interval: 'month',
            interval_count: 1,
            livemode: false,
            metadata: {},
            meter: null,
            nickname: null,
            product: 'prod_QmCwB1erhuDH5n',
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: 'licensed',
          },
          price: {
            id: 'price_1PueW9DWnX2YhQws6s7otplP',
            object: 'price',
            active: true,
            billing_scheme: 'per_unit',
            created: 1725299901,
            currency: 'usd',
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: 'prod_QmCwB1erhuDH5n',
            recurring: {
              aggregate_usage: null,
              interval: 'month',
              interval_count: 1,
              meter: null,
              trial_period_days: null,
              usage_type: 'licensed',
            },
            tax_behavior: 'unspecified',
            tiers_mode: null,
            transform_quantity: null,
            type: 'recurring',
            unit_amount: 1999,
            unit_amount_decimal: '1999',
          },
          quantity: 1,
          subscription: 'sub_1PvJqHDWnX2YhQwsHGDnxFSC',
          tax_rates: [],
        },
      ],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1PvJqHDWnX2YhQwsHGDnxFSC',
    },
    latest_invoice: 'in_1PvJqHDWnX2YhQwscdNfC5qz',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: {
        acss_debit: null,
        bancontact: null,
        card: {
          network: null,
          request_three_d_secure: 'automatic',
        },
        customer_balance: null,
        konbini: null,
        sepa_debit: null,
        us_bank_account: null,
      },
      payment_method_types: null,
      save_default_payment_method: 'off',
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1PueW9DWnX2YhQws6s7otplP',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 1999,
      amount_decimal: '1999',
      billing_scheme: 'per_unit',
      created: 1725299901,
      currency: 'usd',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      meter: null,
      nickname: null,
      product: 'prod_QmCwB1erhuDH5n',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed',
    },
    quantity: 1,
    schedule: null,
    start_date: 1725458753,
    status: 'active',
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: {
      end_behavior: {
        missing_payment_method: 'create_invoice',
      },
    },
    trial_start: null,
  },
  previous_attributes: {
    default_payment_method: null,
    status: 'incomplete',
  },
};

const charge_succeeded = {
  id: 'evt_3Ps2gkDWnX2YhQws0FPgaF3I',
  object: 'event',
  api_version: '2024-06-20',
  created: 1724677831,
  data: {
    object: {
      id: 'ch_3Ps2gkDWnX2YhQws0mXTSRHo',
      object: 'charge',
      amount: 500,
      amount_captured: 500,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: null,
      billing_details: {
        address: {
          city: null,
          country: 'IN',
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: 'business@savibm.com',
        name: 'fsdvd fdsfsef',
        phone: null,
      },
      calculated_statement_descriptor: 'SAVI BM',
      captured: true,
      created: 1724677831,
      currency: 'usd',
      customer: null,
      description: null,
      destination: null,
      dispute: null,
      disputed: false,
      failure_balance_transaction: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: {
        network_status: 'approved_by_network',
        reason: null,
        risk_level: 'normal',
        risk_score: 28,
        seller_message: 'Payment complete.',
        type: 'authorized',
      },
      paid: true,
      payment_intent: 'pi_3Ps2gkDWnX2YhQws0obVnTjZ',
      payment_method: 'pm_1Ps2giDWnX2YhQwsVdqarY6K',
      payment_method_details: {
        card: {
          amount_authorized: 500,
          authorization_code: null,
          brand: 'visa',
          checks: {
            address_line1_check: null,
            address_postal_code_check: null,
            cvc_check: 'pass',
          },
          country: 'US',
          exp_month: 3,
          exp_year: 2025,
          extended_authorization: {
            status: 'disabled',
          },
          fingerprint: 'GMEahrtUyTn0YDqd',
          funding: 'credit',
          incremental_authorization: {
            status: 'unavailable',
          },
          installments: null,
          last4: '4242',
          mandate: null,
          multicapture: {
            status: 'unavailable',
          },
          network: 'visa',
          network_token: {
            used: false,
          },
          overcapture: {
            maximum_amount_capturable: 500,
            status: 'unavailable',
          },
          three_d_secure: null,
          wallet: null,
        },
        type: 'card',
      },
      receipt_email: null,
      receipt_number: null,
      receipt_url:
        'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xUHJjMmdEV25YMlloUXdzKMf9sbYGMgbqjWOh0Rg6LBaCoVnluV_sOOPT-p1q0bJ8rWsC7IxkombcZQ4YXq9FfJ-k3-Q-QmZ5Ghn4',
      refunded: false,
      review: null,
      shipping: null,
      source: null,
      source_transfer: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: 'req_MfdLLtDtxGGuY6',
    idempotency_key: 'e4ed425c-86fd-4b5e-a11b-cdcd16e0c5f7',
  },
  type: 'charge.succeeded',
};

const checkout_session_completed = {
  id: 'evt_1Ps2glDWnX2YhQwszlEbGE9e',
  object: 'event',
  api_version: '2024-06-20',
  created: 1724677831,
  data: {
    object: {
      id: 'cs_test_a1O4VG9kQIvhZo01Rrt5PkbZTHqwZUh7vKVenfM5RsmNBfZZVV89XcJ4LR',
      object: 'checkout.session',
      after_expiration: null,
      allow_promotion_codes: false,
      amount_subtotal: 500,
      amount_total: 500,
      automatic_tax: {
        enabled: false,
        liability: null,
        status: null,
      },
      billing_address_collection: 'auto',
      cancel_url: 'https://stripe.com',
      client_reference_id: null,
      client_secret: null,
      consent: null,
      consent_collection: null,
      created: 1724677628,
      currency: 'usd',
      currency_conversion: null,
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer: null,
      customer_creation: 'if_required',
      customer_details: {
        address: {
          city: null,
          country: 'IN',
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: 'business@savibm.com',
        name: 'fsdvd fdsfsef',
        phone: null,
        tax_exempt: 'none',
        tax_ids: [],
      },
      customer_email: null,
      expires_at: 1724764028,
      invoice: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      livemode: false,
      locale: 'auto',
      metadata: {
        clientid: '918754535859',
      },
      mode: 'payment',
      payment_intent: 'pi_3Ps2gkDWnX2YhQws0obVnTjZ',
      payment_link: 'plink_1Ps2X9DWnX2YhQws4FJcglKp',
      payment_method_collection: 'if_required',
      payment_method_configuration_details: null,
      payment_method_options: {
        card: {
          request_three_d_secure: 'automatic',
        },
      },
      payment_method_types: ['card'],
      payment_status: 'paid',
      phone_number_collection: {
        enabled: false,
      },
      recovered_from: null,
      saved_payment_method_options: null,
      setup_intent: null,
      shipping_address_collection: null,
      shipping_cost: null,
      shipping_details: null,
      shipping_options: [],
      status: 'complete',
      submit_type: 'auto',
      subscription: null,
      success_url: 'https://stripe.com',
      total_details: {
        amount_discount: 0,
        amount_shipping: 0,
        amount_tax: 0,
      },
      ui_mode: 'hosted',
      url: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: null,
    idempotency_key: null,
  },
  type: 'checkout.session.completed',
};

const payment_intent_created = {
  id: 'evt_3Ps2gkDWnX2YhQws0gEPYIJe',
  object: 'event',
  api_version: '2024-06-20',
  created: 1724677830,
  data: {
    object: {
      id: 'pi_3Ps2gkDWnX2YhQws0obVnTjZ',
      object: 'payment_intent',
      amount: 500,
      amount_capturable: 0,
      amount_details: {
        tip: {},
      },
      amount_received: 0,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: 'automatic_async',
      client_secret:
        'pi_3Ps2gkDWnX2YhQws0obVnTjZ_secret_EfV9r4U0RMJwuDYzupKBVXx5b',
      confirmation_method: 'automatic',
      created: 1724677830,
      currency: 'usd',
      customer: null,
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: null,
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: null,
      payment_method_configuration_details: null,
      payment_method_options: {
        card: {
          installments: null,
          mandate_options: null,
          network: null,
          request_three_d_secure: 'automatic',
        },
      },
      payment_method_types: ['card'],
      processing: null,
      receipt_email: null,
      review: null,
      setup_future_usage: null,
      shipping: null,
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'requires_payment_method',
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: 'req_MfdLLtDtxGGuY6',
    idempotency_key: 'e4ed425c-86fd-4b5e-a11b-cdcd16e0c5f7',
  },
  type: 'payment_intent.created',
};

const charge_updated = {
  id: 'evt_3Ps2gkDWnX2YhQws09qdFJwH',
  object: 'event',
  api_version: '2024-06-20',
  created: 1724677834,
  data: {
    object: {
      id: 'ch_3Ps2gkDWnX2YhQws0mXTSRHo',
      object: 'charge',
      amount: 500,
      amount_captured: 500,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: 'txn_3Ps2gkDWnX2YhQws0RpAfzgb',
      billing_details: {
        address: {
          city: null,
          country: 'IN',
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: 'business@savibm.com',
        name: 'fsdvd fdsfsef',
        phone: null,
      },
      calculated_statement_descriptor: 'SAVI BM',
      captured: true,
      created: 1724677831,
      currency: 'usd',
      customer: null,
      description: null,
      destination: null,
      dispute: null,
      disputed: false,
      failure_balance_transaction: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: {
        network_status: 'approved_by_network',
        reason: null,
        risk_level: 'normal',
        risk_score: 28,
        seller_message: 'Payment complete.',
        type: 'authorized',
      },
      paid: true,
      payment_intent: 'pi_3Ps2gkDWnX2YhQws0obVnTjZ',
      payment_method: 'pm_1Ps2giDWnX2YhQwsVdqarY6K',
      payment_method_details: {
        card: {
          amount_authorized: 500,
          authorization_code: null,
          brand: 'visa',
          checks: {
            address_line1_check: null,
            address_postal_code_check: null,
            cvc_check: 'pass',
          },
          country: 'US',
          exp_month: 3,
          exp_year: 2025,
          extended_authorization: {
            status: 'disabled',
          },
          fingerprint: 'GMEahrtUyTn0YDqd',
          funding: 'credit',
          incremental_authorization: {
            status: 'unavailable',
          },
          installments: null,
          last4: '4242',
          mandate: null,
          multicapture: {
            status: 'unavailable',
          },
          network: 'visa',
          network_token: {
            used: false,
          },
          overcapture: {
            maximum_amount_capturable: 500,
            status: 'unavailable',
          },
          three_d_secure: null,
          wallet: null,
        },
        type: 'card',
      },
      receipt_email: null,
      receipt_number: null,
      receipt_url:
        'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xUHJjMmdEV25YMlloUXdzKMr9sbYGMgZQa0JpTCs6LBa7wj5sfSpCupiHoGe142k_VHskOH_lm4d_4PG4TDkseW-5E2PbHLXjuMT3',
      refunded: false,
      review: null,
      shipping: null,
      source: null,
      source_transfer: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
    previous_attributes: {
      balance_transaction: null,
      receipt_url:
        'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xUHJjMmdEV25YMlloUXdzKMr9sbYGMgb5vWB9lDo6LBYovD-RCeE6aDXZurR0mesQmF8rp3eEsakCd2HhTR_7oXpEVj8UzzI5qKRu',
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: null,
    idempotency_key: null,
  },
  type: 'charge.updated',
};
