/* eslint-disable @typescript-eslint/naming-convention */
import Replicate from 'replicate';
import { v4 as uuidv4 } from 'uuid';

import {
  getUserLoraDetails,
  uploadFileToFirebase,
} from '@/utils/ReplyHelper/FirebaseHelpers';

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});

const MULTI_LORA_TEMP_MODEL =
  'lucataco/flux-dev-multi-lora:a738942df15c8c788b076ddd052256ba7923aade687b12109ccc64b2c3483aa1';
const REALISM_LORA_URL =
  'https://firebasestorage.googleapis.com/v0/b/paparazzi-ai.appspot.com/o/private%2Fcustom_models%2Fflux_realism_lora.safetensors?alt=media&token=e390b666-4c3a-4726-b94a-41395a9d98aa&filename=realismlora.safetensors';

export async function generateImagesWithReplicateUploadToFirebase(
  improvedPromptFromGroq: string,
  clientid: string,
): Promise<string[]> {
  try {
    const clientLoraInfo = await getUserLoraDetails(clientid);
    const lora_url = clientLoraInfo.loraURL;
    const lora_filename = clientLoraInfo.loraFilename;

    const output = await replicate.run(MULTI_LORA_TEMP_MODEL, {
      input: {
        prompt: improvedPromptFromGroq,
        hf_loras: [`${lora_url}&filename=${lora_filename}`, REALISM_LORA_URL],
        num_outputs: 1,
        aspect_ratio: '9:16',
        output_format: 'png',
        guidance_scale: 3.5,
        output_quality: 80,
        num_inference_steps: 28,
      },
    });

    console.log('[+] Replicate output:', JSON.stringify(output, null, 2));

    if (!Array.isArray(output) || output.length === 0) {
      console.warn('No images were generated by Replicate.');
      return [];
    }

    const foldername = 'replicate_images';

    const processPromises = output.map(
      async (imageUrl: string, index: number) => {
        try {
          const response = await fetch(imageUrl);
          const arrayBuffer = await response.arrayBuffer();
          const base64Content = Buffer.from(arrayBuffer).toString('base64');

          const filename = `${clientid || 'test'}_${uuidv4()}_${index + 1}.png`;
          const firebaseUrl = await uploadFileToFirebase(
            base64Content,
            clientid,
            foldername,
            filename,
          );
          return firebaseUrl;
        } catch (error) {
          console.error('Error processing image:', error);
          return null;
        }
      },
    );

    const results = await Promise.all(processPromises);
    const firebaseURLs = results.filter((url): url is string => url !== null);

    return firebaseURLs;
  } catch (error) {
    console.error(
      'Error generating images with Replicate and uploading to Firebase:',
      error,
    );
    throw new Error('Failed to generate and upload images');
  }
}
